---

- name: add zabbix repository key
  apt_key: url=https://repo.zabbix.com/zabbix-official-repo.key state=present

- name: "add zabbix repository {{ zabbix_version }}"
  apt_repository:
    repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} main"
    state: present
  with_items:
    - deb-src
    - deb

- name: installing zabbix-agent
  apt: name=zabbix-agent state=latest

- name: make sure zabbix log directory exists
  file:
    path: /var/log/zabbix/
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory

- name: adding zabbix config
  template: src=zabbix_agentd.conf.j2
            dest=/etc/zabbix/zabbix_agentd.conf
            owner=root
            group=root
            mode=0644

- name: add psk
  copy: content="{{ monitoring_zabbix_key_psk }}" dest=/etc/zabbix/key.psk

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted
  changed_when: False

- name: enable agent on boot zabbix-agent
  service: name=zabbix-agent enabled=yes
  changed_when: False

#- name: enable agent on boot zabbix-agent
#  shell: systemctl enable zabbix-agent
#  changed_when: False
